### ISSUE TITLE
Question about the find_ancs.py？

### ISSUE THREAD

**Issue by Kihensarn** [zipengxuc/PPE-Pytorch#2]
Hello, after runing the find_ancs.py, I'm not sure the texts in atrs.json is sorted in ascending order or descending order？Could you tell me the details？

**Comment by zipengxuc** [comment]
Hello, the higher the ranking, the higher the possibility of entanglement. For example, the 1st one is the predicted most possibly entangled attribute.

**Comment by Kihensarn** [comment]
Sorry, I also want to know whether the texts I get in the atrs.json is sorted in ascending order or descending order？

**Comment by zipengxuc** [comment]
The 1st text is the 1st possibly entangled attribute, the 2nd is the 2nd possibly entangled attribute, and so on...
Hope this resolves your issue.
